services:
  user_app:
    build:
    context: ./
    dockerfile: Dockerfile
    env_file:
      - .env.local

    # environment:
    #   - name=value

    ports:
      - "3000:3000"

    depends_on:
      - 
